---
- name: Install fish
  become: true
  package:
    name: fish
    state: installed
  when: only_config is not defined

- name: Create fish config directory
  file:
    path: "~/.config/fish"
    state: directory

- name: Symlink fish config files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.config/fish/{{ item }}"
    state: link
  with_items:
    - config.fish
    - prompt.fish
    - personal.fish

- name: Create directory for fish functions
  file:
    path: "~/.config/fish/functions"
    state: directory

- name: Install fundle (fish plugin manager)
  get_url:
    url: https://git.io/fundle
    dest: "~/.config/fish/functions/fundle.fish"

- name: Symlink fish prompt file
  file:
    src: "{{ role_path }}/files/fish_prompt.fish"
    dest: "~/.config/fish/functions/fish_prompt.fish"
    state: link
