---
- hosts: localhost
  roles:
    - fish
    - bash
    - python
    - git
    - neovim
    - tmux
    - links
    - less
    - ranger
    - network-tools
    - utilities
    - user
    - sudo
    - locale
    - timezone
