---
- hosts: localhost
  roles:
    - i3
    - fonts
    - dunst
    - lightdm
    - chromium
    - firefox
    - xfce-terminal
    - dmenu
    - gui-utilities
    - xcape
    - pulseaudio
    - multiscreen
