---
# TODO check if works on Debian

- name: Install xorg group
  become: yes
  package:
    name: xorg
    state: installed

- name: Install video driver
  become: yes
  package:
    name: xf86-video-intel
    state: installed

- name: Ensure proper xinitrc in place
  copy:
    src: xinitrc
    dest: "{{ ansible.HOME }}/.xinitrc"
