[theme]
name = "solarized-light"

[icons]
name = "awesome"

[[block]]
block = "custom"
command = "xsel -o"
on_click = "xsel -c"
interval = 1

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
speed_up = false
speed_down = false

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{SUg}+{MUg}GB ({MUp}%)"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "battery"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "time"
interval = 60
format = "%a %d.%m %R"
on_click = "gsimplecal"
