---
- name: Install NetworkManager and applet
  become: true
  package:
    name: "{{ item }}"
  with_items:
    - networkmanager
    - network-manager-applet

- name: Enable NetworkManager.service
  become: yes
  systemd:
    name: NetworkManager
    enabled: true

