---
- name: Install packages for a firmware engineer
  become: true
  package:
    name: "{{ item }}"
  with_items:
    - ubuntu-desktop
    # General tools
    - fish
    - tmux
    - git
    - python3-pip
    - gh
    - neovim
    - sixv
    - ansible
    - p7zip-full
    - unrar
    - xxd
    - tio
    - ripgrep
    - ranger
    - openssl
    - meld
    - flameshot
    - ffmpeg
    # Hardware/Firmware tools
    - edid-decode
    - ddcutil
    - s-tui
    - stress
    - powercap-utils
    - acpica-tools
    - lsscsi
    - lm-sensors
    - i2c-tools
    - wireshark
    - fwts
    - usbutils
    - pciutils
    - tpm2-tools
    - sg3-utils
    - powertop
    - nvme-cli
    - mokutil
    - hwinfo
    - linux-tools-common
    - htop
    # Firmware update
    - flashrom
    - dfu-util
    - uefitool
    # Sound/Video
    - alsa-utils
    - pulseaudio-utils
    - guvcview
    - pavucontrol
      # TODO: sof-ctl
    # Already included in Ubuntu 24.04
    - fwupd
    - hdparm
    - fprintd
  when: only_config is not defined
