---
- name: Install packages for a firmware engineer
  become: true
  when: only_config is not defined
  package:
    name: "{{ item }}"
  with_items:
    # General tools
    - sudo
    - fish
    - tmux
    - git
    - python3
    - gh
    - neovim
    - unrar
    - xxd
    - tio
    - ripgrep
    - openssl
    - meld
    - flameshot
    - ffmpeg
    - colordiff
    # Hardware/Firmware tools
    - edid-decode
    - s-tui
    - stress
    - stress-ng
    - acpica-tools
    - i2c-tools
    - wireshark
    - usbutils
    - pciutils
    - tpm2-tools
    - nvme-cli
    - htop
    - sdparm
    # Firmware update
    - flashrom
    - dfu-util
    # Sound/Video
    - alsa-utils
    - pavucontrol
      # TODO: sof-ctl
    - fprintd

- name: Install packages for a firmware engineer
  when: only_config is not defined
  become: true
  when: ansible_facts['os_family'] == "RedHat"
  package:
    name: "{{ item }}"
  with_items:
    - python3-pip
    - ansible
    - sxiv
    - ranger
    - p7zip
    - ddcutil
    - lsscsi
    - fwts
    - powertop
    - mokutil
    - hwinfo
    - fwupd
    - hdparm
    - powerstat
    - pulseaudio-utils
    - alsa-ucm-utils
    - guvcview
    # Different name
    - lm_sensors
    - sg3_utils
    - kernel-tools

- name: Install packages for a firmware engineer
  become: true
  when: only_config is not defined
  when: ansible_facts['os_family'] == "Debian"
  package:
    name: "{{ item }}"
  with_items:
    - python3-pip
    - ansible
    - sxiv
    - ranger
    - p7zip
    - ddcutil
    - lsscsi
    - fwts
    - powertop
    - mokutil
    - hwinfo
    - fwupd
    - hdparm
    - powerstat
    - pulseaudio-utils
    - alsa-ucm-utils
    - guvcview
    # Different name
    - lm-sensors
    - sg3-utils
    - linux-tools-common
    # Not on Fedora
    - ubuntu-desktop
    - uefitool
    - powercap-utils
    - p7zip-full

- name: Install packages for a firmware engineer
  become: true
  when: only_config is not defined
  when: ansible_facts['os_family'] == "FreeBSD"
  package:
    name: "{{ item }}"
  with_items:
    # FreeBSD tools
    - sysinfo
    # Different name
    - py39-pip
    - py39-ansible
    - py39-ranger
    - nsxiv
    - 7-zip
    # Not packaged yet
    # - mokutil
    # - hwinfo
    # - fwupd
    # - hdparm
    # - powerstat
    # - ddcutil
    # - lsscsi
    # - fwts
    # - pulseaudio-utils # linux-c7-pulseaudio-utils
    # - alsa-ucm-utils
    # - guvcview
