---
- name: Install packages for a firmware engineer
  become: true
  when: only_config is not defined
  package:
    name: "{{ item }}"
  with_items:
    # General tools
    - fish
    - tmux
    - git
    - python3-pip
    - gh
    - neovim
    - sxiv
    - ansible
    - unrar
    - xxd
    - tio
    - ripgrep
    - ranger
    - openssl
    - meld
    - flameshot
    - ffmpeg
    - colordiff
    - p7zip
    # Hardware/Firmware tools
    - edid-decode
    - ddcutil
    - s-tui
    - stress
    - acpica-tools
    - lsscsi
    - i2c-tools
    - wireshark
    - fwts
    - usbutils
    - pciutils
    - tpm2-tools
    - powertop
    - nvme-cli
    - mokutil
    - hwinfo
    - htop
    # Firmware update
    - flashrom
    - dfu-util
    # Sound/Video
    - alsa-utils
    - alsa-ucm-utils
    - pulseaudio-utils
    - guvcview
    - pavucontrol
      # TODO: sof-ctl
    # Already included in Ubuntu 24.04
    - fwupd
    - hdparm
    - fprintd
    - powerstat

- name: Install packages for a firmware engineer
  when: only_config is not defined
  become: true
  when: ansible_facts['os_family'] == "RedHat"
  package:
    name: "{{ item }}"
  with_items:
    # Different name
    - lm_sensors
    - sg3_utils
    - kernel-tools

- name: Install packages for a firmware engineer
  become: true
  when: only_config is not defined
  when: ansible_facts['os_family'] == "Debian"
  package:
    name: "{{ item }}"
  with_items:
    # Different name
    - lm-sensors
    - sg3-utils
    - linux-tools-common
    # Not on Fedora
    - ubuntu-desktop
    - uefitool
    - powercap-utils
    - p7zip-full
