---
- name: Install pip
  become: true
  apt:
    name: python-pip
    state: installed

- name: Symlink python config file
  file:
    src: "{{ role_path }}/files/pythonrc"
    dest: "~/.pythonrc"
    state: link
