---
- name: Install pip
  become: true
  package:
    name: python-pip
    state: latest
  when: only_config is not defined

- name: Symlink python config file
  file:
    src: "{{ role_path }}/files/pythonrc"
    dest: "~/.pythonrc"
    state: link
