---
- name: Install less
  become: true
  package:
    name: less
    state: latest
  when: only_config is not defined

- name: Symlink lesskey file (less config)
  file:
    src: "{{ role_path  }}/files/lesskey"
    dest: "~/.lesskey"
    state: link
  when: ansible_os_family != "NixOS"

- name: Generate less config
  shell: lesskey
  when: ansible_os_family != "NixOS"
