---
- name: Install gui-utilities
  become: true
  package:
    name: "{{ item }}"
  with_items:
    - evince
    - nautilus
    - xsel
    - thunderbird
    - keepass
    - feh
  when: only_config is not defined
