---
- name: Install git
  become: true
  package:
    name: git
    state: installed
  when: only_config is not defined

- name: Create git config directory
  file:
    path: ~/.config/git
    state: directory

- name: Symlink config files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.config/git/{{ item }}"
    state: link
  with_items:
    - config
    - ignore
    - gitmessage_template

- fail:
    msg: "Variable git_name or git_email is not defined."
  when: git_name == "" or git_email == "" or git_name is undefined or git_email is undefined

- name: Copy templated gitconfig to final destination
  template:
    src: "{{ role_path }}/templates/git/templates/my_git_user_config.j2"
    dest: "~/.config/git/my_git_user_config"
