---
- name: Install git
  become: true
  package:
    name: git
    state: installed

- name: Symlink config files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.{{ item }}"
    state: link
  with_items:
    - gitattributes
    - gitconfig
    - gitfiles

# TODO Ensure username and email are set
