" Section: Mappings {{{
let mapleader=","                           " set leader to , (Comma)

noremap <leader>ev :e $MYVIMRC<cr> " open .vimrc with <leader>ev
noremap <leader>sv :so $MYVIMRC<cr>" open .vimrc with <leader>sv

" move in wrapped line as if they were separate
" flip meaning of j and gj, and k and gk
nnoremap k gk
nnoremap j gj
vnoremap k gk
vnoremap j gj
nnoremap gk k
nnoremap gj j
vnoremap gk k
vnoremap gj j

noremap  <leader><space> :nohlsearch<cr><leader><space> " turn off search highlight
nnoremap <space> za                         " toggle fold on spacebar
nnoremap <silent><leader>w :%s/\s\+$//<cr>  " delete all trailing whitespace
vnoremap <c-a> <esc>ggVG                    " select entire file
" }}}

" Section: Plugins {{{

" vim-plug Plugin manager
" install vim-plug:
" $ curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
"     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
if 1 " TODO: should check if vim-plug is installed
  call plug#begin('~/.vim/plugged')

  " Plugins: In use {{{

  " show git diff +, -, ~ at the left
  Plug 'airblade/vim-gitgutter'
  "set updatetime=250

  " cp to copy to system-Clipboard
  " cP to copy line and cv to paste to next line
  " REQUIRES xsel to be installed or clip and paste on Windows
  Plug 'christoomey/vim-system-copy'

  " surround with s
  Plug 'tpope/vim-surround'

  " repeat plugin commands
  Plug 'tpope/vim-repeat'

  Plug 'vimwiki/vimwiki'
  "let g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
  let g:vimwiki_list = [{'syntax': 'markdown', 'ext': '.md'}]
  let g:vimwiki_global_ext = 0
  " }}}

  " Plugins: Testing {{{
  "}}}

  " Plugins: Unused {{{
  " }}}

  call plug#end()
endif

" }}}

" Section: OS-Specific {{{

if has("win32")
  " Windows {{{

  set backupdir=$HOME\_vim\backup\\
  set directory=$HOME\_vim\tmp\\

  " }}}
else
  " Linux {{{

  " move the backup and temp files somewhere else so they don't clutter up the
  " current directory
  set backupdir=$HOME/.vim/backup//
  set directory=$HOME/.vim/tmp//

  " }}}
endif

" }}}

" Section: Experimental {{{
" }}}

" Section: Options {{{

set encoding=utf-8                          " force utf8 support
syntax on                                   " syntax highlighting
" }}}

" Section: To be reviewed {{{
" }}}

" vim: foldmethod=marker
