" Section: Mappings {{{
" }}}

" Section: Plugins {{{

" vim-plug Plugin manager
" install vim-plug:
" $ curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
"     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
if 1 " TODO: should check if vim-plug is installed
  call plug#begin('~/.vim/plugged')

  " Plugins: In use {{{
  " }}}

  " Plugins: Testing {{{
  "}}}

  " Plugins: Unused {{{
  " }}}

  call plug#end()
endif

" }}}

" Section: OS-Specific {{{

if has("win32")
  " Windows {{{

  set backupdir=$HOME\_vim\backup\\
  set directory=$HOME\_vim\tmp\\

  " }}}
else
  " Linux {{{

  " move the backup and temp files somewhere else so they don't clutter up the
  " current directory
  set backupdir=$HOME/.vim/backup//
  set directory=$HOME/.vim/tmp//

  " }}}
endif

" }}}

" Section: Experimental {{{
" }}}

" Section: Options {{{

set encoding=utf-8                          " force utf8 support
syntax on                                   " syntax highlighting
" }}}

" Section: To be reviewed {{{
" }}}

" vim: foldmethod=marker
