---
- name: Install xfce-terminal
  become: true
  package:
    name: xfce4-terminal
    state: installed
  when: only_config is not defined

- name: Ensure xfce4 config dir is present
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "~/.config/xfce4"
    - "~/.config/xfce4/terminal"

- name: Symlink xfce4-terminal config
  file:
    src: "{{ role_path }}/files/terminalrc"
    dest: "~/.config/xfce4/terminal/terminalrc"
    state: link
