---
- name: Install tmux
  become: true
  package:
    name: tmux
    state: installed
  when: only_config is not defined

- name: Symlink config and theme
  become: true
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.{{ item }}"
    state: link
  with_items:
    - tmux.conf
    - tmux_theme.conf
  when: ansible_os_family != "NixOS"
