---
- name: Install lightdm and gtk greeter
  become: true
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    lightdm-gtk-greeter

- name: Enable lightdm
  become: true
  service:
    name: lightdm
    enabled: true
