---
- name: Install lightdm and gtk greeter
  become: true
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    lightdm-gtk-greeter
  when: only_config is not defined

- name: Enable lightdm
  become: true
  service:
    name: lightdm
    enabled: true
  when: ansible_os_family != "NixOS"

- name: Download GitHub profile picture
  get_url:
    url: "https://github.com/{{ github_username }}.png?size=96"
    dest: $HOME/.face
