---
- name: Install xcape
  become: true
  package:
    name: xcape
    state: installed

- name: Map capslock to ctrl and escape in Xorg
  lineinfile:
    path: "{{ ansible.HOME }}/.xprofile"
    line: "{{ item }}"
  with_items:
    - "xcape -e 'Caps_Lock=Escape'             # Map Caps-Lock to Escape"
    - "setxkbmap -option 'caps:ctrl_modifier'  # Map Caps-Lock-modifier to Ctrl"
