---
- name: Install vim
  become: true
  apt:
    name: vim-nox
    state: installed

- name: Create directories for backup and temporary files
  file:
    path: "~/.vim/{{ item }}"
    state: directory
  with_items:
    - tmp
    - backup
    - autoload

- name: Install vim-plug plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: Symlink vimrc
  file:
    src: "{{ role_path }}/files/vimrc"
    dest: "~/.vimrc"
    state: link

- name: Install plugins
  command: vim +PlugInstall +qall
