---
- name: Download Fantasque Sans Mono
  get_url:
    url: https://github.com/belluzj/fantasque-sans/releases/download/v1.7.1/FantasqueSansMono.tar.gz
    dest: /tmp/FantasqueSansMono.tar.gz

- name: Extract Fantasque Sans Mono
  unarchive:
    src: /tmp/FantasqueSansMono.tar.gz
    dest: /tmp/fonts

- name: Install Fantasque Mono
  become: true
  copy:
    src: "{{ item }}"
    dest: /usr/share/fonts/
  with_fileglob: "/tmp/fonts/*.ttf"
