---
- name: Download Font Awesome
  get_url:
    url: http://fontawesome.io/assets/font-awesome-4.7.0.zip
    dest: /tmp/font-awesome-4.7.0.zip

- name: Extract Font Awesome
  unarchive:
    src: /tmp/font-awesome-4.7.0.zip
    dest: /tmp/fonts/

- name: Install Font Awesome
  become: true
  copy:
    src: "{{ item }}"
    dest: /usr/share/fonts/
  with_fileglob: "/tmp/fonts/font-awesome-4.7.0/fonts/*"
